services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend-mongo
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/kairo
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

volumes:
  mongo-data:
